### ISSUE TITLE
Unable to use in cordova 3.2

### ISSUE THREAD

**Issue by DCRichards** [jrstarke/webview-debug#2]
Unable to use this plugin in Cordova 3.2 as the android_parser.js file has been changed so the android target is no longer specified explicitly, it appears cordova 3.2 is hard coded to use android-18.

**Comment by jrstarke** [comment]
Thanks for bringing this to my attention @DCRichards, I will try to figure this out tonight.  In the mean time, I had a quick look at the source code, and I can't seem to find where they are explicitly hard coding that it has to have andoird-18 now. Have you tried just changing the project properties to use android-19?

**Comment by DCRichards** [comment]
Thank you for such a quick reply, much appreciated! I can't find it either, there are various places where there are references to the android target in some kind of variable but no indication of where this comes from in the first place, but it is shown as android-18 when you deploy. Regarding your last point, the way my project works the api version in project properties comes from cordova at build time so changes beforehand will just get overwritten so it would be preferable to work around this rather than change the process.

**Comment by jrstarke** [comment]
Unfortunately, I can't seem to be of much help. I created a new project, updated my cordova to 3.2.0, updated the android platform for the project, and then check my project.properties.  Apparently, mine is now generated with android-19.

**Comment by DCRichards** [comment]
Not a problem, for now I have a workaround anyway changing the 18 to 19 post-build so I guess it's just a waiting game for Cordova to target 19 by default. Thanks very much for your help and great work on the plugin.

**Comment by jrstarke** [comment]
Actually, it appears that in the next release, they will have the Remote Debugging enabled by default 

https://github.com/apache/cordova-android/commit/ea1f041e1167de9add5346a7d4fe6afec095d910#commitcomment-4737926

**Comment by DCRichards** [comment]
That's awesome, thank you again for investigating for me

**Comment by smazurov** [comment]
yup you can get it now by `npm install cordova@3.3.0-rc1` then running `cordova update android`
